INFO:root:A new inforomation request came
ERROR:root:division by zero
Traceback (most recent call last):
  File "C:\Users\admin\PycharmProjects\TreenetraClass\ExceptionHandeling\exception_handeling.py", line 88, in <module>
    print(x/y)
          ~^~
ZeroDivisionError: division by zero
INFO:root:Request Processing Completed
